recorder:
  ros__parameters:
    topics:
      - /zed/left/camera_info
      - /zed/left/image_raw/compressed 
      
      # --- Tópicos Externos (Via Rede) ---
      - /slam/map/markers
      - /slam/map
      - /slam/pose
      - /slam/stats
      - /path
      - /path/markers
      - /control/feedback
      - /control/rpm_target
      - /control/torque_target
      - /control/target/marker
      - /state
      - /state/nodes
      - /mission
      - /imu/angular_velocity
      - /imu/acceleration
      - /imu/gnss_pose
      - /jetson
      -
      -
      -

    storage_id: "mcap"
    serialization_format: "cdr"
    start_recording_immediately: false 